buildscript {
    ext.kotlin_version = '2.2.10'
    repositories {
        google()
        mavenCentral()
        maven {
            url "https://oss.sonatype.org/content/repositories/snapshots"
        }
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:9.3.2'
    }
}

plugins {
    id 'com.android.legacy-kapt' version '9.3.2' apply false
}

